name: Backend CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./blackend

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: blackend/package-lock.json

      - name: 📦 Install Dependencies
        run: npm install

      - name: ✅ Run Tests (Optional)
        run: echo "No tests to run"

      - name: 🏗️ Check Build (Optional)
        run: echo "No build step"